default: &default
  app_key: "3280876495"
  client_secret: "b1c4c542339b3957f63c89c210c9c206"
  redirect_uri: "http://hi.iqunix.com/users/weibo/callback"

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
